### PR TITLE
Correct gitlab link

### PR DESCRIPTION
**Pull request by icarito**
Also, gitlab is out of sync.
Do you still prefer issues tracked at Gitlab? Thanks!

### CODE REVIEW

**Comment by azazel75** [comment]
Hi Sebastian,

the link is correct, it's not wrong... and yes, I would like more to have issues and pull requests submitted on gitlab the repository here is just a mirror. I talked with a developer who had his repo  shut down on github beacause something he committed was considered a DMCA violation. Scary...gitlab is better and at least is free software. The top would be to have something like gitlab in Europe... 

BTW, how is that you started using pj? Last time I tracked your efforts you were using Transcrypt.

**Comment by azazel75** [comment]
I'll deal with the PRs that you submitted here anyway

**Comment by icarito** [comment]
Thanks! Check your gitlab repo settings, https://gitlab.com/metapensiero/metapensiero.pj doesn't exist for me! maybe it's private?

**Comment by azazel75** [comment]
WTF! it was private, thanks!

**Comment by icarito** [comment]
Alberto, thanks for your response to my requests! Did you get notification from Gitlab for https://gitlab.com/metapensiero/metapensiero.pj/merge_requests/35 ? :-D Thanks in advance

**Pull request closed without merging**
